Source Code/AdminPortal/AdminPortal/Models/Restaurant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.AppUsers = new HashSet<AppUser>();
            this.Tags = new HashSet<Tag>();
            this.Transmitters = new HashSet<Transmitter>();
            this.AppUserStats = new HashSet<AppUserStat>();
<<<<<<< HEAD
            this.AspNetUsers = new HashSet<AspNetUser>();
=======
            this.Zones = new HashSet<Zone>();
>>>>>>> origin/master
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte[] Map { get; set; }
        public string Admin { get; set; }
    
        public virtual ICollection<AppUser> AppUsers { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Transmitter> Transmitters { get; set; }
        public virtual ICollection<AppUserStat> AppUserStats { get; set; }
<<<<<<< HEAD
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
=======
        public virtual ICollection<Zone> Zones { get; set; }
>>>>>>> origin/master
    }
}

Source Code/AdminPortal/AdminPortal/Controllers/RestaurantsController.cs
using AdminPortal.Models;

using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AdminPortal.Controllers {

	[Authorize]
	public class RestaurantsController : Controller {
		private KinderFinderEntities db = new KinderFinderEntities();

		// Used to retrieve stored images.
		public FileContentResult GetMap(int? id) {
			if (!User.IsInRole("GlobalAdmins") || id == null)
				return null;

			Restaurant restaurant = db.Restaurants.Find(id);

			if (restaurant == null || restaurant.Map == null)
				return null;

			return new FileContentResult(restaurant.Map, "image/jpeg");
		}

		// GET: Restaurants
		public ActionResult Index() {
			if (!User.IsInRole("GlobalAdmins"))
				return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

			return View(db.Restaurants.ToList());
		}

		// GET: Restaurants/Details/5
		public ActionResult Details(int? id) {
			if (!User.IsInRole("GlobalAdmins"))
				return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Restaurant restaurant = db.Restaurants.Find(id);
			if (restaurant == null) {
				return HttpNotFound();
			}
			return View(restaurant);
		}

		// GET: Restaurants/Create
		public ActionResult Create() {
			if (!User.IsInRole("GlobalAdmins"))
				return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

			ViewBag.Admin = new SelectList(db.AspNetUsers, "Id", "Email");

			return View();
		}

		// POST: Restaurants/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "ID,Name,Map,Admin")] Restaurant restaurant, HttpPostedFileBase file) {
			if (ModelState.IsValid) {
				if (file != null) {
					MemoryStream target = new MemoryStream();
					file.InputStream.CopyTo(target);
					restaurant.Map = target.ToArray();
				}

				db.Restaurants.Add(restaurant);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(restaurant);
		}

		// GET: Restaurants/Edit/5
		public ActionResult Edit(int? id) {
			if (!User.IsInRole("GlobalAdmins"))
				return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Restaurant restaurant = db.Restaurants.Find(id);
			if (restaurant == null) {
				return HttpNotFound();
			}
			ViewBag.Admin = new SelectList(db.AspNetUsers, "Id", "Email", restaurant.Admin);
			return View(restaurant);
		}

		// POST: Restaurants/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "ID,Name,Map,Admin")] Restaurant restaurant, HttpPostedFileBase file) {
			if (ModelState.IsValid) {
				if (file != null) {
					MemoryStream target = new MemoryStream();
					file.InputStream.CopyTo(target);
					restaurant.Map = target.ToArray();
				}

				db.Entry(restaurant).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(restaurant);
		}

		// GET: Restaurants/Delete/5
		public ActionResult Delete(int? id) {
			if (!User.IsInRole("GlobalAdmins"))
				return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Restaurant restaurant = db.Restaurants.Find(id);
			if (restaurant == null) {
				return HttpNotFound();
			}
			return View(restaurant);
		}

		// POST: Restaurants/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int? id) {
			Restaurant restaurant = db.Restaurants.Find(id);
			db.Restaurants.Remove(restaurant);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing) {
			if (disposing) {
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

Source Code/AdminPortal/AdminPortal/Controllers/WebAPI/Restaurants/LinkRestaurantController.cs
using AdminPortal.Models;

using System;
using System.Linq;
using System.Web.Http;

namespace AdminPortal.Controllers.WebAPI.Restaurants {

	/**
	 * Links a user to a restaurant.
	 */
	public class LinkRestaurantController : ApiController {
		private KinderFinderEntities db = new KinderFinderEntities();

		[HttpPost]
		public IHttpActionResult PickRestaurant(RequestDetails details) {
			var user = (from item in db.AppUsers
						where item.EmailAddress.Equals(details.EmailAddress, StringComparison.CurrentCultureIgnoreCase)
						select item).FirstOrDefault();

			var restaurant = (from item in db.Restaurants
						where item.Name.Equals(details.Restaurant)
						select item).FirstOrDefault();

			if (user == null || restaurant == null)
				return BadRequest();

			user.CurrentRestaurant = restaurant.ID;
			db.SaveChanges();

			return Ok();
		}

		public struct RequestDetails {
			public string EmailAddress,
				Restaurant;
		}
	}
}

Source Code/AdminPortal/AdminPortal/Controllers/WebAPI/Restaurants/RestaurantListController.cs
using AdminPortal.Models;

using System.Collections.Generic;
using System.Web.Http;

namespace AdminPortal.Controllers.WebAPI.Restaurants {

	/**
	 * Simply retrieves a list of all restaurants in the system.
	 */
	public class RestaurantListController : ApiController {
		private KinderFinderEntities db = new KinderFinderEntities();

		[HttpPost]
		public IHttpActionResult GetRestaurants() {
			var result = new List<string>();

			foreach (var item in db.Restaurants)
				result.Add(item.Name);

			return Ok(result);
		}
	}
}

Source Code/AdminPortal/AdminPortal/Views/Restaurants/Create.cshtml
@model AdminPortal.Models.Restaurant

@{
    ViewBag.Title = "Add New Restaurant";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Create", "Restaurants", null, FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <!-- NAME -->
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- MAP -->
        <div class="form-group">
            @Html.Label("Map", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="Data" title="Upload" />
            </div>
        </div>

        <!-- ADMINISTRATOR -->
        <div class="form-group">
            @Html.LabelFor(model => model.Admin, "Admin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Admin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Admin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Source Code/AdminPortal/AdminPortal/Views/Restaurants/Delete.cshtml
@model AdminPortal.Models.Restaurant

@{
    ViewBag.Title = "Delete Restaurant";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this restaurant?</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <!-- NAME -->
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <!-- MAP -->
        <dt>
            @Html.DisplayNameFor(model => model.Map)
        </dt>
        <dd>
            @if (Model.Map != null) {
                <img src="@Url.Action("GetMap", "Restaurants", new { id = Model.ID })" alt="Map image" />
            }
            else {
                @Html.Raw("(none)");
            }
        </dd>

        <!-- ADMINISTRATOR -->
        <dt>
            @Html.DisplayNameFor(model => model.Admin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AspNetUser.UserName)
            (<a href="mailto:@Model.AspNetUser.Email">@Model.AspNetUser.Email</a>)
        </dd>

        <!-- DELETE BUTTON -->
        <dt></dt>
        <dd>
            @using (Html.BeginForm()) {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" />
                </div>
            }
        </dd>
    </dl>

    <div class="form-actions no-color">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Source Code/AdminPortal/AdminPortal/Views/Restaurants/Details.cshtml
@model AdminPortal.Models.Restaurant

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <!-- NAME -->
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <!-- Map -->
        <dt>
            @Html.DisplayNameFor(model => model.Map)
        </dt>
        <dd>
            @if (Model.Map != null) {
                <img src="@Url.Action("GetMap", "Restaurants", new { id = Model.ID })" alt="Map image" />
            }
            else {
                @Html.Raw("(none)");
            }
        </dd>

        <!-- ADMINISTRATOR -->
        <dt>
            @Html.Raw("Administrator")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AspNetUser.UserName)
            (<a href="mailto:@Model.AspNetUser.Email">@Model.AspNetUser.Email</a>)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Source Code/AdminPortal/AdminPortal/Views/Restaurants/Edit.cshtml
@model AdminPortal.Models.Restaurant

@{
    ViewBag.Title = "Edit Restaurant";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Restaurants", null, FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    bool hasImage = Model.Map != null;

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Map)

        <!-- NAME -->
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- EXISTING MAP -->
        <div class="form-group">
            @Html.Label("Existing Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (hasImage) {
                    <img src="@Url.Action("GetMap", "Restaurants", new { id = Model.ID })" alt="Map image" /><br />
                    @Html.ActionLink("Delete Image", "DeleteImage", new { id = Model.ID }, htmlAttributes: new { @class = "btn btn-default" })
                }
                else {
                    @Html.Raw("(none)")
                }
            </div>
        </div>

        <!-- NEW MAP -->
        <div class="form-group">
            @Html.Label("New Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <br />
                <input type="file" name="file" id="file" title="Upload" /><br />
                @if (hasImage) {
                    @Html.Raw("<p><b>Note:</b> <i>If no new image is chosen, the current image will be kept.</i></p>")
                }
            </div>
        </div>

        <!-- ADMINISTRATOR -->
        <div class="form-group">
            @Html.LabelFor(model => model.Admin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Admin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Admin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Source Code/AdminPortal/AdminPortal/Views/Restaurants/Index.cshtml
@model IEnumerable<AdminPortal.Models.Restaurant>

@{
    ViewBag.Title = "List of Restaurants";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Add New Restaurant", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Admin)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.UserName)
                (<a href="mailto:@item.AspNetUser.Email">@item.AspNetUser.Email</a>)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>